/***************************************
                |GROUP-09|
  Aditya Upadhyay      -   2017A7PS0083P
  Harpider Jot Singh   -   2017A7PS0057P
  Jaladi Lakshmi Teja  -   2017A7PS0068P
  Vishal Mittal        -   2017A7PS0080P
  Yash Vijay           -   2017A7PS0072P
*****************************************/
#include "lexer.h"
#include "parser.h"
#include "treeADT.h"
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <time.h>

void print_menu() {
  printf("\t\t MENU\n");
  printf("-----------------------------------------------------------------\n");
  printf("1. Remove comments from the source code\n");
  printf("2. Print tokens generated by lexer\n");
  printf("3. Print parse tree for the program\n");
  printf("4. Print time taken for tokenizing and parsing\n");
  printf("5. Print first sets\n");
  printf("6. Print follow sets\n");
  printf(" Press any other to exit \n");
  printf("-----------------------------------------------------------------\n");
  printf("Enter your choice:  ");
}

int main(int argc, char *argv[]) {

  if (argc < 2) {
    printf("\n\nUsage: make file=<test_case_file_name>\n\n");
    exit(1);
  }

  setvbuf(stdout, NULL, _IONBF, 0);

  int choice;
  char source_file[100];
  strcpy(source_file, argv[1]);

  FILE *source = fopen(source_file, "r");
  if (source == NULL) {
    printf("Error opening file\n");
  }

  while (true) {
      print_menu();
      scanf("%d", &choice);
      printf("\n");

      switch (choice) {
      case 1: 
      {
        // fseek(source, 0, SEEK_SET);
		lexer_init(source);
        char no_comment_file[100];
        printf("Enter name of the output file which will have the source code without comments\n");
        scanf("%s", no_comment_file);
		remove_comments(source, no_comment_file);
      } break;

      case 2: 
      {
        lexer_init(source);
        tokenize_source_file(source);
      } break;

      case 3: {

        lexer_init(source);
        parser_init();

        FILE *fptr = fopen("grammar.txt", "r");
        if (fptr == NULL) {
          perror("fopen");
        }
        grammar_fill(fptr); 
        
        populate_first_sets();

        populate_follow_sets();

        create_parse_table();

        tree_node *ptr = parse_input_source_code(source);

        if (ptr == NULL) 
		    {
          printf("Empty parse tree\n");
        }

        // print_parse_table();
        print_parse_tree(ptr);

        free_grammar();
        fclose(fptr);

      } break;
      case 4: {
        clock_t start_time, end_time;

        double total_CPU_time, total_CPU_time_in_seconds;

        start_time = clock();

        // FILE *source = fopen("test.txt", "r");
        lexer_init(source);
        parser_init();

        // print_token_stream(source);

        FILE *fptr = fopen("grammar.txt", "r");
        if (fptr == NULL) {
          perror("fopen");
        }
        grammar_fill(fptr);

        populate_first_sets();

        populate_follow_sets();

        // reset_lexer_dfa(source);

        // fseek(source, 0, SEEK_SET);

        create_parse_table();
        // ull *fset = get_rule_first_set(grammar[0].head);
        // print_parse_table();

        tree_node *ptr = parse_input_source_code(source);

        // free(source);
        fclose(fptr);

        end_time = clock();

        total_CPU_time = (double)(end_time - start_time);

        total_CPU_time_in_seconds = total_CPU_time / CLOCKS_PER_SEC;

        printf(
            "Total CPU TIME taken (in microseconds): %lf usecs\nTotal CPU time (in seconds)\t      : %lf secs\n",
            total_CPU_time, total_CPU_time_in_seconds);

      } break;
      case 5: {
        lexer_init(source);
        parser_init();

        FILE *fptr = fopen("grammar.txt", "r");
        if (fptr == NULL) {
          perror("fopen");
        }
        grammar_fill(fptr);

        populate_first_sets();

        print_first_sets();

        fclose(fptr);
      } break;
      case 6: 
      {
          lexer_init(source);
          parser_init();

          FILE *fptr = fopen("grammar.txt", "r");
          if (fptr == NULL) 
		  {
            perror("fopen");
          }
          grammar_fill(fptr);

          populate_first_sets();

          populate_follow_sets();
          print_follow_sets();

          fclose(fptr);
          break;
      } 
      default: 
      {
        // break;
        exit(0);
      } break;
    }// end of switch
  }
  fclose(source);
} // end of main
