src = $(wildcard *.c)

exe:
	@echo "\nCOMPILING..."
	@gcc $(src) -lm
	@echo "\nCOMPILED SUCCESSFULLY..."
	@echo "\n Run the file as ./a.out <testcase file> <parse tree output file>"
#	./a.out ${file} ${pfile}
